import "./globals.css";
import { Nunito } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import ClientOnly from "./components/clientOnlyProps";
import Modal from "./components/modals/modal";

const font = Nunito({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <Modal actionLabel={""} isOpen={true} title={'hello world'} />
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
