import "./globals.css";
import { Nunito } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import ClientOnly from "./components/clientOnlyProps";
import RegisterdModal from './components/modals/RegisterdModal'
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/modals/LoginModal"
import getCurrentUser from "../app/actions/getCurrentUser"
import RentModal from "./components/modals/RentModal";

const font = Nunito({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterdModal />
          <LoginModal />
          <RentModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  );
}
